export { mountComponent } from '../component/index.ts'
export { mountChild } from './child.ts'
export { mountChildren } from './children.ts'
export { mountElement } from './element.ts'
export type { MountedHandle } from './handle.ts'
export { mountVirtualNode } from './virtual-node.ts'
