export { createApp, renderDomRoot as render } from './create-app.ts'
export type { DomAppInstance } from './create-app.ts'
export { invokerCacheKey } from './patch-props.ts'
export type { ElementRef } from './patch-props.ts'
export { domRendererOptions } from './renderer-options.ts'
